-- MySQL Script generated by MySQL Workbench
-- Fri Feb 21 21:06:44 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MyCMS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MyCMS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MyCMS` DEFAULT CHARACTER SET utf8 ;
USE `MyCMS` ;

-- -----------------------------------------------------
-- Table `MyCMS`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyCMS`.`User` (
  `UserID` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(50) NOT NULL,
  `Password` VARCHAR(255) NOT NULL,
  `Role` ENUM('ADMIN', 'NORMAL') NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `FirstName` VARCHAR(50) NULL DEFAULT NULL,
  `LastName` VARCHAR(50) NULL DEFAULT NULL,
  `LastLogin` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`UserID`),
  UNIQUE INDEX (`Username` ASC) VISIBLE,
  UNIQUE INDEX (`Email` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `MyCMS`.`Company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyCMS`.`Company` (
  `CompanyID` INT NOT NULL AUTO_INCREMENT,
  `CompanyName` VARCHAR(100) NOT NULL,
  `Industry` VARCHAR(50) NULL DEFAULT NULL,
  `Street` VARCHAR(100) NULL DEFAULT NULL,
  `City` VARCHAR(50) NULL DEFAULT NULL,
  `State` VARCHAR(50) NULL DEFAULT NULL,
  `Zip` VARCHAR(20) NULL DEFAULT NULL,
  `Country` VARCHAR(50) NULL DEFAULT NULL,
  `Phone` VARCHAR(20) NULL DEFAULT NULL,
  `Email` VARCHAR(100) NULL DEFAULT NULL,
  `Website` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`CompanyID`),
  UNIQUE INDEX (`CompanyName` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `MyCMS`.`Contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyCMS`.`Contact` (
  `ContactID` INT NOT NULL AUTO_INCREMENT,
  `UserID` INT NOT NULL,
  `FirstName` VARCHAR(50) NOT NULL,
  `LastName` VARCHAR(50) NOT NULL,
  `DateOfBirth` DATE NOT NULL,
  `Gender` ENUM('M', 'F', 'Other') NULL DEFAULT NULL,
  `Street` VARCHAR(100) NULL DEFAULT NULL,
  `City` VARCHAR(50) NULL DEFAULT NULL,
  `State` VARCHAR(50) NULL DEFAULT NULL,
  `Zip` VARCHAR(20) NULL DEFAULT NULL,
  `Country` VARCHAR(50) NULL DEFAULT NULL,
  `CompanyID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ContactID`),
  INDEX (`UserID` ASC) VISIBLE,
  INDEX (`CompanyID` ASC) VISIBLE,
  CONSTRAINT `fk_Contact_User`
    FOREIGN KEY (`UserID`)
    REFERENCES `MyCMS`.`User` (`UserID`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_Contact_Company`
    FOREIGN KEY (`CompanyID`)
    REFERENCES `MyCMS`.`Company` (`CompanyID`)
    ON DELETE SET NULL);


-- -----------------------------------------------------
-- Table `MyCMS`.`ContactNickname`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyCMS`.`ContactNickname` (
  `NicknameID` INT NOT NULL AUTO_INCREMENT,
  `ContactID` INT NOT NULL,
  `Nickname` VARCHAR(50) NOT NULL,
  `CreatedDate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedDate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`NicknameID`, `ContactID`),
  INDEX (`ContactID` ASC) VISIBLE,
  CONSTRAINT `fk_ContactNickname_Contact`
    FOREIGN KEY (`ContactID`)
    REFERENCES `MyCMS`.`Contact` (`ContactID`)
    ON DELETE CASCADE);


-- -----------------------------------------------------
-- Table `MyCMS`.`Phone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyCMS`.`Phone` (
  `PhoneID` INT NOT NULL AUTO_INCREMENT,
  `ContactID` INT NOT NULL,
  `PhoneNumber` VARCHAR(20) NOT NULL,
  `PhoneType` ENUM('Cell', 'Home', 'Work', 'Fax') NOT NULL,
  `CountryCode` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`PhoneID`),
  INDEX (`ContactID` ASC) VISIBLE,
  CONSTRAINT `fk_Phone_Contact`
    FOREIGN KEY (`ContactID`)
    REFERENCES `MyCMS`.`Contact` (`ContactID`)
    ON DELETE CASCADE);


-- -----------------------------------------------------
-- Table `MyCMS`.`Email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyCMS`.`Email` (
  `EmailID` INT NOT NULL AUTO_INCREMENT,
  `ContactID` INT NOT NULL,
  `EmailAddress` VARCHAR(100) NOT NULL,
  `EmailType` ENUM('Personal', 'Work', 'Other') NOT NULL,
  `IsPrimary` TINYINT NULL DEFAULT FALSE,
  PRIMARY KEY (`EmailID`),
  INDEX (`ContactID` ASC) VISIBLE,
  CONSTRAINT `fk_Email_Contact`
    FOREIGN KEY (`ContactID`)
    REFERENCES `MyCMS`.`Contact` (`ContactID`)
    ON DELETE CASCADE);


-- -----------------------------------------------------
-- Table `MyCMS`.`Picture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyCMS`.`Picture` (
  `PictureID` INT NOT NULL AUTO_INCREMENT,
  `ImagePath` VARCHAR(255) NULL DEFAULT NULL,
  `UploadedDate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `Description` TEXT NULL DEFAULT NULL,
  `Contact_ContactID` INT NOT NULL,
  PRIMARY KEY (`PictureID`),
  INDEX `fk_Picture_Contact1_idx` (`Contact_ContactID` ASC) VISIBLE,
  CONSTRAINT `fk_Picture_Contact1`
    FOREIGN KEY (`Contact_ContactID`)
    REFERENCES `MyCMS`.`Contact` (`ContactID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `MyCMS`.`ActivityType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyCMS`.`ActivityType` (
  `ActivityTypeID` INT NOT NULL AUTO_INCREMENT,
  `TypeName` VARCHAR(50) NOT NULL,
  `Description` TEXT NULL DEFAULT NULL,
  `CreatedAt` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ActivityTypeID`),
  UNIQUE INDEX (`TypeName` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `MyCMS`.`ActivityLog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyCMS`.`ActivityLog` (
  `LogID` INT NOT NULL AUTO_INCREMENT,
  `UserID` INT NOT NULL,
  `ActivityTypeID` INT NOT NULL,
  `Timestamp` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `Description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`LogID`),
  INDEX (`UserID` ASC) VISIBLE,
  INDEX (`ActivityTypeID` ASC) VISIBLE,
  CONSTRAINT `fk_ActivityLog_User`
    FOREIGN KEY (`UserID`)
    REFERENCES `MyCMS`.`User` (`UserID`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_ActivityLog_ActivityType`
    FOREIGN KEY (`ActivityTypeID`)
    REFERENCES `MyCMS`.`ActivityType` (`ActivityTypeID`)
    ON DELETE CASCADE);


-- -----------------------------------------------------
-- Table `MyCMS`.`ContactNote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyCMS`.`ContactNote` (
  `NoteID` INT NOT NULL AUTO_INCREMENT,
  `ContactID` INT NOT NULL,
  `NoteTitle` VARCHAR(100) NULL DEFAULT NULL,
  `NoteText` TEXT NULL DEFAULT NULL,
  `CreatedDate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `LastModified` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Status` ENUM('ACTIVE', 'REMOVED') NULL DEFAULT 'ACTIVE',
  PRIMARY KEY (`NoteID`),
  INDEX (`ContactID` ASC) VISIBLE,
  CONSTRAINT `fk_ContactNote_Contact`
    FOREIGN KEY (`ContactID`)
    REFERENCES `MyCMS`.`Contact` (`ContactID`)
    ON DELETE CASCADE);


-- -----------------------------------------------------
-- Table `MyCMS`.`GroupTable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyCMS`.`GroupTable` (
  `GroupID` INT NOT NULL AUTO_INCREMENT,
  `GroupName` VARCHAR(100) NOT NULL,
  `Description` TEXT NULL DEFAULT NULL,
  `CreatedDate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `Status` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`GroupID`),
  UNIQUE INDEX (`GroupName` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `MyCMS`.`ContactGroupMapping`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyCMS`.`ContactGroupMapping` (
  `ContactID` INT NOT NULL,
  `GroupID` INT NOT NULL,
  `DateAdded` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `MappingStatus` ENUM('ACTIVE', 'INACTIVE') NULL DEFAULT 'ACTIVE',
  INDEX (`ContactID` ASC) VISIBLE,
  INDEX (`GroupID` ASC) VISIBLE,
  PRIMARY KEY (`ContactID`, `GroupID`),
  CONSTRAINT `fk_ContactGroupMapping_Contact`
    FOREIGN KEY (`ContactID`)
    REFERENCES `MyCMS`.`Contact` (`ContactID`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_ContactGroupMapping_Group`
    FOREIGN KEY (`GroupID`)
    REFERENCES `MyCMS`.`GroupTable` (`GroupID`)
    ON DELETE CASCADE);


-- -----------------------------------------------------
-- Table `MyCMS`.`Tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyCMS`.`Tag` (
  `TagID` INT NOT NULL AUTO_INCREMENT,
  `TagName` VARCHAR(50) NOT NULL,
  `Description` TEXT NULL DEFAULT NULL,
  `CreatedDate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `TagColor` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`TagID`),
  UNIQUE INDEX (`TagName` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `MyCMS`.`ContactTagMapping`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyCMS`.`ContactTagMapping` (
  `ContactID` INT NOT NULL,
  `TagID` INT NOT NULL,
  `CreatedTime` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `Status` ENUM('ACTIVE', 'REMOVED') NULL DEFAULT 'ACTIVE',
  PRIMARY KEY (`ContactID`, `TagID`),
  INDEX (`ContactID` ASC) VISIBLE,
  INDEX (`TagID` ASC) VISIBLE,
  CONSTRAINT `fk_ContactTagMapping_Contact`
    FOREIGN KEY (`ContactID`)
    REFERENCES `MyCMS`.`Contact` (`ContactID`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_ContactTagMapping_Tag`
    FOREIGN KEY (`TagID`)
    REFERENCES `MyCMS`.`Tag` (`TagID`)
    ON DELETE CASCADE);


-- -----------------------------------------------------
-- Table `MyCMS`.`Meeting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyCMS`.`Meeting` (
  `MeetingID` INT NOT NULL AUTO_INCREMENT,
  `UserID` INT NOT NULL,
  `MeetingTitle` VARCHAR(100) NOT NULL,
  `Description` TEXT NULL DEFAULT NULL,
  `Location` VARCHAR(200) NULL DEFAULT NULL,
  `MeetingDate` DATETIME NOT NULL,
  `CreatedDate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`MeetingID`),
  INDEX (`UserID` ASC) VISIBLE,
  CONSTRAINT `fk_Meeting_User`
    FOREIGN KEY (`UserID`)
    REFERENCES `MyCMS`.`User` (`UserID`)
    ON DELETE CASCADE);


-- -----------------------------------------------------
-- Table `MyCMS`.`MeetingContactMapping`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyCMS`.`MeetingContactMapping` (
  `MeetingID` INT NOT NULL,
  `ContactID` INT NOT NULL,
  `InvitationStatus` ENUM('Accepted', 'Declined', 'Pending') NULL DEFAULT 'Pending',
  `ResponseDate` DATETIME NULL DEFAULT NULL,
  INDEX (`MeetingID` ASC) VISIBLE,
  INDEX (`ContactID` ASC) VISIBLE,
  PRIMARY KEY (`MeetingID`, `ContactID`),
  CONSTRAINT `fk_MeetingContactMapping_Meeting`
    FOREIGN KEY (`MeetingID`)
    REFERENCES `MyCMS`.`Meeting` (`MeetingID`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_MeetingContactMapping_Contact`
    FOREIGN KEY (`ContactID`)
    REFERENCES `MyCMS`.`Contact` (`ContactID`)
    ON DELETE CASCADE);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;